# -*- coding: utf-8 -*-
"""a00_read_gaskap_pilot_data_cube_MW_fg-Cp5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ji2nYjR-NogQQiGMF-z5-KxZKyQwYAc

# Connect and authorize google drive
"""

# from google.colab import drive
# drive.mount('/content/gdrive')
# !ls

"""# Libs"""

import os

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

from scipy import signal
from scipy.optimize import curve_fit
from scipy.interpolate import interp1d

import random
from dataclasses import dataclass
from typing import List, Tuple, Optional
import pandas as pd

import math
import pickle
import glob

# from scipy.signal import find_peaks
from scipy.ndimage import gaussian_filter
from astropy.convolution import Gaussian2DKernel, convolve_fft

from tqdm import tqdm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

from astropy.io          import fits
from astropy             import units as u
from astropy.coordinates import SkyCoord
from astropy.wcs         import WCS

from pathlib import Path

# from spectral_cube import SpectralCube

"""# Path"""

home_path = Path('/home/100/vn9735/')
base_path = home_path / 'tpc'
checkpoint_path = base_path / 'checkpoints'
img_path = base_path / 'figs'
checkpoint_path

sc_path = Path('/scratch/xt61/vn9735/')

data_path     = sc_path / 'data'
uma_data_path = data_path / 'UMA'

saury2014_data_path = data_path # 'saury'
saury_data_path = data_path # 'saury'
seta222_data_path = data_path   # 'seta'
print(checkpoint_path)
print('UMA: ', uma_data_path)
print('Saury 2014: ', saury2014_data_path)

cube_path = data_path / 'cube'

hires_data_path = data_path / 'hires'
hires_results = hires_data_path / 'results'
abs_data_path = hires_data_path / 'abs'
em_data_path = hires_data_path / 'neighbour_emission_spectra_20241011'
print(data_path)
print(hires_data_path)
print(em_data_path)
print(abs_data_path)

"""# For plotting"""

# Define the Gaussian function
def gaussian(v, tb, vlsr, sigma):
    return tb * np.exp(-(v - vlsr)**2 / (2 * sigma**2))

"""# Read GASKAP data cube"""

# gaskap_pilot_cube = cube_path / 'Tb_combined_mw_fg_full.fits'
# gaskap_pilot_cube = cube_path / 'Tb_combined_mw_fg_1km_30arcsec_central_region.fits'
# gaskap_pilot_cube = cube_path / 'Tb_combined_mw_fg_1km_30arcsec_central_region2.fits'
gaskap_pilot_cube = cube_path / 'Tb_combined_mw_fg_1km_30arcsec_central_region3.fits'

cube, hdr = fits.getdata(gaskap_pilot_cube, header=True)

cube = cube.astype(np.float32)

cube[cube < -3.] = 0.

# sigma defines the 'heaviness' of the smoothing for each axis (nchan, ny, nx)
# Example: sigma=1 smooths slightly across all three dimensions
# smoothed_cube = gaussian_filter(cube, sigma=(1, 2, 2))


# Define parameters
pixel_scale = 6.0  # Replace with your actual arcsec/pixel
theta_kernel_arcsec = np.sqrt(60.**2 - 30.**2) # 30'' to 60''
sigma_pixels = theta_kernel_arcsec / (2.355 * pixel_scale)

# sigma is applied to (nchan, ny, nx)
# We use 0 for nchan because we only want to smooth spatially
sigma_spat = sigma_pixels
smoothed_cube = gaussian_filter(cube, sigma=(0., sigma_spat, sigma_spat))

nchan, ny, nx = cube.shape
print('nchans, ny, nx:', nchan, ny, nx)

crval = hdr['CRVAL3']/1000.
print('crval: ', crval)

cdelt = hdr['CDELT3']/1000.
print('cdelt: ', cdelt)

crpix = hdr['CRPIX3']
print('crpix: ', crpix)

vchans = np.arange(1, nchan + 1)
vaxis = crval + (vchans - crpix) * cdelt

# vaxis = vaxis/1000.
# vaxis

# 1. Create the mapping indices
# We map the 256 new slots across the 118 old slots
print(nchan)
old_indices = np.arange(nchan)
new_indices = np.linspace(0, nchan-1, 256)

# 2. Interpolate both Spectrum AND Velocity
# new_spectrum = np.interp(new_indices, old_indices, tb_tot_gfit)
v = np.interp(new_indices, old_indices, vaxis)

# Create the interpolation function along the velocity axis (axis=0)
f = interp1d(old_indices, smoothed_cube, kind='cubic', axis=0)
resampled_cube = f(new_indices)

gaskap_nspecs = ny * nx
print('gaskap_nspecs: ', gaskap_nspecs)

dv = hdr['CDELT3'] / 1000.
print('dv:', dv)

wcs3D = WCS(hdr)
print(wcs3D)

wcs2D = wcs3D.celestial
wcs2D

m0_map = np.sum(cube, axis=0)*dv

nhi = 0.018224*m0_map

nchan, ny, nx = resampled_cube.shape
print(nchan, ny, nx)

# Define the testing region
test_start = 1100
test_end = 1244

# Extract testing data (the middle stripe)
resampled_test_cube = resampled_cube[:, test_start:test_end, :].copy()
nchan, ny_test, nx_test = resampled_test_cube.shape
print(nchan, ny_test, nx_test, nx_test*ny_test)

# Extract training data (everything except the middle stripe)
# train_data_top = data_cube[:, :test_start, :]      # ny from 0 to 200
# train_data_bottom = data_cube[:, test_end:, :]      # ny from 400 to 1055

resampled_train_cube_top = resampled_cube[:, :test_start, :]
resampled_train_cube_bot = resampled_cube[:, test_end:, :]
resampled_train_cube = np.concatenate([resampled_train_cube_top, resampled_train_cube_bot], axis=1)
nchan, ny_train, nx_train = resampled_train_cube.shape
print(nchan, ny_train, nx_train, nx_train*ny_train)

# cube_rs = cube.reshape(-1, nchan, order='C')
cube_rs_all = resampled_train_cube.reshape(nchan, ny_train * nx_train).T
# tau_cube_rs = tau_cube.reshape(nchan, ny * nx).T
# ts_cube_rs = ts_cube.reshape(nchan, ny * nx).T

# Combine all data cubes: more than 1 million spectra
# cube_rs_all = np.concatenate([cube_rs, cube1_rs, cube2_rs],
#                               axis=0
#                             )
print(cube_rs_all.shape)

"""# Physics-constrained autoencoder"""

class PhysicsLayer(nn.Module):
    """
    HI 21cm radiative transfer physics layer.
    TB = T_HI * (1 - exp(-tau))
    """
    def __init__(self):
        super(PhysicsLayer, self).__init__()

    def forward(self, log10_T_HI, tau):
        """
        Args:
            log10_T_HI: log10 of HI spin temperature (batch, 256)
            tau: optical depth (batch, 256)
        Returns:
            TB: brightness temperature (batch, 256)
        """
        T_HI = 10. ** log10_T_HI
        TB = T_HI * (1. - torch.exp(-tau))
        return TB

class Encoder(nn.Module):
    """
    Encoder: emission spectrum -> latent distribution parameters
    Using Conv1D for better spectral feature extraction
    """
    def __init__(self, input_dim=256, latent_dim=64):
        super(Encoder, self).__init__()

        # Convolutional layers for spectral features
        self.conv_layers = nn.Sequential(
            nn.Conv1d(1, 32, kernel_size=5, padding=2),
            nn.BatchNorm1d(32),
            nn.LeakyReLU(0.2),
            nn.MaxPool1d(2),  # 256 -> 128

            nn.Conv1d(32, 64, kernel_size=5, padding=2),
            nn.BatchNorm1d(64),
            nn.LeakyReLU(0.2),
            nn.MaxPool1d(2),  # 128 -> 64

            nn.Conv1d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm1d(128),
            nn.LeakyReLU(0.2),
            nn.MaxPool1d(2),  # 64 -> 32

            nn.Conv1d(128, 128, kernel_size=3, padding=1),
            nn.BatchNorm1d(128),
            nn.LeakyReLU(0.2),
        )

        # Fully connected layers
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 32, 256),
            nn.BatchNorm1d(256),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.2)
        )

        # Output: mean and log_variance for the latent distribution
        self.fc_mu = nn.Linear(256, latent_dim)
        self.fc_logvar = nn.Linear(256, latent_dim)

    def forward(self, x):
        # x shape: (batch, 256)
        x = x.unsqueeze(1)  # (batch, 1, 256) for Conv1d
        h = self.conv_layers(x)
        h = self.fc(h)
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        # Clamp logvar to prevent numerical instability
        logvar = torch.clamp(logvar, -10, 10)
        return mu, logvar

class Decoder(nn.Module):
    """
    Decoder: latent -> (log10_T_HI, tau)
    Using transposed convolutions for upsampling
    """
    def __init__(self, latent_dim=64, output_dim=256):
        super(Decoder, self).__init__()

        self.fc = nn.Sequential(
            nn.Linear(latent_dim, 256),
            nn.BatchNorm1d(256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 128 * 32),
            nn.BatchNorm1d(128 * 32),
            nn.LeakyReLU(0.2)
        )

        # Transposed conv for upsampling
        self.deconv_layers = nn.Sequential(
            nn.Unflatten(1, (128, 32)),  # (batch, 128, 32)

            nn.ConvTranspose1d(128, 128, kernel_size=4, stride=2, padding=1),  # 32 -> 64
            nn.BatchNorm1d(128),
            nn.LeakyReLU(0.2),

            nn.ConvTranspose1d(128, 64, kernel_size=4, stride=2, padding=1),  # 64 -> 128
            nn.BatchNorm1d(64),
            nn.LeakyReLU(0.2),

            nn.ConvTranspose1d(64, 32, kernel_size=4, stride=2, padding=1),  # 128 -> 256
            nn.BatchNorm1d(32),
            nn.LeakyReLU(0.2),
        )

        # Separate heads for physical parameters
        self.conv_log10_T_HI = nn.Conv1d(32, 1, kernel_size=3, padding=1)
        self.conv_tau = nn.Conv1d(32, 1, kernel_size=3, padding=1)

    def forward(self, z):
        h = self.fc(z)
        h = self.deconv_layers(h)

        # log10_T_HI typically in range [1, 4] (10K to 10000K)
        log10_T_HI = self.conv_log10_T_HI(h).squeeze(1)  # (batch, 256)
        log10_T_HI = torch.sigmoid(log10_T_HI) * 3 + 1.  # range: [1, 4]
        # log10_T_HI = torch.clamp(log10_T_HI, 0.45, 4.122)

        # tau typically in range [0, 10]
        tau = self.conv_tau(h).squeeze(1)  # (batch, 256)
        tau = F.softplus(tau)

        return log10_T_HI, tau

class HI_VAE(nn.Module):
    """
    Variational Autoencoder for HI radiative transfer with physics layer
    """
    def __init__(self, spectrum_dim=256, latent_dim=64):
        super(HI_VAE, self).__init__()

        self.encoder = Encoder(spectrum_dim, latent_dim)
        self.decoder = Decoder(latent_dim, spectrum_dim)
        self.physics_layer = PhysicsLayer()
        self.latent_dim = latent_dim

    def reparameterize(self, mu, logvar):
        """
        Reparameterization trick: z = mu + sigma * epsilon
        """
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, TB_obs):
        """
        Forward pass through VAE
        """
        # Encode
        mu, logvar = self.encoder(TB_obs)

        # Sample from latent distribution
        z = self.reparameterize(mu, logvar)

        # Decode to physical parameters
        log10_T_HI, tau = self.decoder(z)

        # Apply physics layer
        TB_recon = self.physics_layer(log10_T_HI, tau)

        return TB_recon, log10_T_HI, tau, mu, logvar

    def sample_posterior(self, TB_obs, n_samples=512):
        """
        Sample from posterior distribution p(T_HI, tau | TB_obs)
        """
        self.eval()
        with torch.no_grad():
            mu, logvar = self.encoder(TB_obs)

            T_HI_samples = []
            tau_samples = []
            TB_samples = []

            for _ in range(n_samples):
                z = self.reparameterize(mu, logvar)
                log10_T_HI, tau = self.decoder(z)
                TB_recon = self.physics_layer(log10_T_HI, tau)

                T_HI_samples.append(10. ** log10_T_HI)
                tau_samples.append(tau)
                TB_samples.append(TB_recon)

            return (torch.stack(T_HI_samples),
                    torch.stack(tau_samples),
                    torch.stack(TB_samples))

def vae_loss(TB_recon, TB_obs, log10_T_HI, tau, mu, logvar, beta=1., lambda_tspin_prior=10., smoothness_weight=1.):
    """
    VAE loss = reconstruction loss + KL divergence

    Args:
        TB_recon: reconstructed brightness temperature
        TB_obs: observed brightness temperature
        mu: latent mean
        logvar: latent log variance
        beta: weight for KL divergence (beta-VAE)
    """
    beta = 1.
    lambda_tspin_prior = 1.
    # Reconstruction loss (MSE)
    # recon_loss = F.mse_loss(TB_recon, TB_obs, reduction='sum') / TB_obs.size(0)

    # Main reconstruction loss (MSE)
    recon_loss = nn.MSELoss()(TB_recon, TB_obs)

    # KL divergence
    kl_loss = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())


    # Smoothness loss - penalize large differences between adjacent channels
    # This encourages smooth spectra and reduces "comb" artifacts
    diff = TB_recon[:, 1:] - TB_recon[:, :-1]
    smoothness_loss = torch.mean(diff ** 2)

    # Second derivative (curvature) penalty for even smoother results
    second_diff = TB_recon[:, 2:] - 2 * TB_recon[:, 1:-1] + TB_recon[:, :-2]
    curvature_loss = torch.mean(second_diff ** 2)

    # Combined smoothness term
    smooth_term = smoothness_loss + 0.5 * curvature_loss



    # Compute expected T_spin from predicted tau
    # Add small epsilon to avoid division by zero
    # ts_expected_sims = 30. * ((1. - np.exp(-tau_peak_vals))**(-0.68) )
    epsilon = 1.e-6
    factor = (1. - torch.exp(-tau)) # + epsilon
    T_spin_expected = 30. * torch.pow(factor, -0.68)
    # T_spin_expected = 28.4 * torch.pow(factor, -0.48)
    log10_T_spin_expected = torch.log10(T_spin_expected + epsilon)

    # Penalize deviation from expected T_spin
    # Only apply where tau is reasonable (avoid extreme values)
    # tau_mask = (tau > 0.005) & (tau < 50.)  # Valid tau range
    # tau_mask = (tau > 0.000001) & (tau < 50.)  # Valid tau range
    # tspin_prior_loss = torch.mean(
    #     tau_mask.float() * (log10_T_HI - log10_T_spin_expected)**2
    # )

    tspin_prior_loss = torch.mean((log10_T_HI - log10_T_spin_expected)**2)

    total_loss = recon_loss + beta*kl_loss + lambda_tspin_prior*tspin_prior_loss + smoothness_weight * smooth_term
    return total_loss, recon_loss, kl_loss, tspin_prior_loss, smooth_term

# # Dataset class
# class HISpectrumDataset(Dataset):
#     def __init__(self, emission_spectra):
#         """
#         Args:
#             emission_spectra: numpy array of shape (n_samples, 256)
#         """
#         self.emission = torch.FloatTensor(emission_spectra)

#     def __len__(self):
#         return len(self.emission)

#     def __getitem__(self, idx):
#         return self.emission[idx]


# Dataset class
class HISpectrumDataset(Dataset):
    def __init__(self, emission_spectra, normalize=False):
        """
        Args:
            emission_spectra: numpy array of shape (n_samples, 256)
            normalize: whether to normalize the data
        """
        self.emission = torch.FloatTensor(emission_spectra)
        self.normalize = normalize

        if normalize:
            self.mean = self.emission.mean(dim=0, keepdim=True)
            self.std = self.emission.std(dim=0, keepdim=True) + 1e-8
            self.emission = (self.emission - self.mean) / self.std

    def __len__(self):
        return len(self.emission)

    def __getitem__(self, idx):
        return self.emission[idx]

    def denormalize(self, x):
        if self.normalize:
            return x * self.std + self.mean
        return x

"""# Training"""

# Training function
def train_vae(model, dataloader, optimizer, device, epoch, n_epochs, beta_schedule='constant', beta_max=1.):
    model.train()
    total_loss = 0.
    total_recon = 0.
    total_kl = 0.
    total_ts_prior = 0.
    total_smooth = 0.

    # Beta annealing
    if beta_schedule == 'linear':
        beta = min(beta_max, beta_max * epoch / (n_epochs * 0.5))
    elif beta_schedule == 'cyclical':
        cycle = epoch % (n_epochs // 4)
        beta = min(beta_max, beta_max * cycle / (n_epochs // 8))
    else:  # constant
        beta = beta_max

    for batch in dataloader:
        TB_obs = batch.to(device)

        # Forward pass
        TB_recon, log10_T_HI, tau, mu, logvar = model(TB_obs)

        # Compute loss
        loss, recon_loss, kl_loss, ts_prior_loss, smooth_loss = vae_loss(TB_recon, TB_obs, log10_T_HI, tau, mu, logvar, beta=beta)

        # Backward pass
        optimizer.zero_grad()
        loss.backward()

        # Gradient clipping to prevent exploding gradients
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        optimizer.step()

        total_loss += loss.item()
        total_recon += recon_loss.item()
        total_kl += kl_loss.item()
        total_ts_prior += ts_prior_loss.item()
        total_smooth += smooth_loss.item()
    # End - for: batch

    n_batches = len(dataloader)
    return total_loss/n_batches, total_recon/n_batches, total_kl/n_batches, total_ts_prior/n_batches, total_smooth/n_batches, beta

def validate(model, dataloader, device, beta=1.):
    """Validation function"""
    model.eval()

    total_loss = 0.
    total_recon = 0.
    total_kl = 0.
    total_ts_prior = 0.
    total_smooth = 0.

    with torch.no_grad():
        for batch in dataloader:
            TB_obs = batch.to(device)
            TB_recon, log10_T_HI, tau, mu, logvar = model(TB_obs)

            # Compute loss
            # loss, recon_loss, kl_loss = vae_loss(TB_recon, TB_obs, mu, logvar, beta)
            loss, recon_loss, kl_loss, ts_prior_loss, smooth_loss = vae_loss(TB_recon, TB_obs, log10_T_HI, tau, mu, logvar, beta=beta)

            total_loss += loss.item()
            total_recon += recon_loss.item()
            total_kl += kl_loss.item()
            total_ts_prior += ts_prior_loss.item()
            total_smooth += smooth_loss.item()
        # End - for: batch
    # End - with

    n_batches = len(dataloader)
    return total_loss/n_batches, total_recon/n_batches, total_kl/n_batches, total_ts_prior/n_batches, total_smooth / n_batches

def train_model(model, train_loader, val_loader, lr=0.001, device='cuda', num_epochs=100, beta_schedule='constant', beta_max=1.):
    """
    Training loop for the physics-constrained autoencoder.
    """
    model = model.to(device)

    # Use Adam with weight decay
    # optimizer = optim.Adam(model.parameters(), lr=lr)
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-5)

    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min',
                                                      factor=0.5, patience=5)

    history = {
        'total_loss': [],
        'recon_loss': [],
        'kl_loss': [],
        'ts_prior_loss': [],
        'smooth_loss': [],

        'val_total_loss': [],
        'val_recon_loss': [],
        'val_kl_loss': [],
        'val_ts_prior_loss': [],
        'val_smooth_loss': [],
    }

    # Training loop
    print("Training VAE...")
    best_val_loss = float('inf')

    for epoch in range(num_epochs):
        epoch_losses = {'total': 0., 'recon': 0., 'smooth': 0., 'sparse': 0., 'kl':0., 'ts_prior': 0.,
                       'val_total': 0., 'val_recon': 0., 'val_smooth': 0., 'val_sparse': 0., 'val_kl':0., 'val_ts_prior': 0.}

        loss, recon, kl, ts_loss, smooth, beta = train_vae(model, train_loader, optimizer, device, epoch, num_epochs,
                                                   beta_schedule=beta_schedule, beta_max=beta_max)
        val_loss, val_recon, val_kl, val_ts, val_smooth = validate(model, val_loader, device, beta=beta)

        # Track losses
        epoch_losses['total'] = loss
        epoch_losses['recon'] = recon
        epoch_losses['kl'] = kl
        epoch_losses['ts_prior'] = ts_loss
        epoch_losses['smooth'] = smooth

        epoch_losses['val_total'] = val_loss
        epoch_losses['val_recon'] = val_recon
        epoch_losses['val_kl'] = val_kl
        epoch_losses['val_ts_prior'] = val_ts
        epoch_losses['val_smooth'] = val_smooth

        history['total_loss'].append(epoch_losses['total'])
        history['recon_loss'].append(epoch_losses['recon'])
        history['kl_loss'].append(epoch_losses['kl'])
        history['ts_prior_loss'].append(epoch_losses['ts_prior'])
        history['smooth_loss'].append(epoch_losses['smooth'])

        history['val_total_loss'].append(epoch_losses['val_total'])
        history['val_recon_loss'].append(epoch_losses['val_recon'])
        history['val_kl_loss'].append(epoch_losses['val_kl'])
        history['val_ts_prior_loss'].append(epoch_losses['val_ts_prior'])
        history['val_smooth_loss'].append(epoch_losses['val_smooth'])

        # Learning rate scheduling
        # scheduler.step(epoch_losses['total']) # recon, LATER, check with "total" loss
        scheduler.step(val_loss)

        if val_loss < best_val_loss:
            print('Saving best model...')
            best_val_loss = val_loss
            torch.save(model.state_dict(), 'best_vae_model_a00_smooth_mod11_mw_1100_1200.pt')

        # Print progress
        if (epoch + 1) % 10 == 0:
            print(f"Epoch [{epoch+1}/{num_epochs}]")
            print(f"  Train: Total: {epoch_losses['total']:.4f}, Recon: {epoch_losses['recon']:.4f}")
            print(f"         KL: {epoch_losses['kl']:.4f}")
            print(f"         Ts prior: {epoch_losses['ts_prior']:.4f}")
            print(f"         smooth: {epoch_losses['smooth']:.4f}")

            print(f"  Val: Total: {epoch_losses['val_total']:.4f}, Recon: {epoch_losses['val_recon']:.4f}")
            print(f"         KL: {epoch_losses['val_kl']:.4f}")
            print(f"         Ts prior: {epoch_losses['val_ts_prior']:.4f}")
            print(f"         Smooth: {epoch_losses['val_smooth']:.4f}")

            print(f"  Beta: {beta:.4f}")

    return history

# GPU or CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
ngpus = torch.cuda.device_count()
print('device: ', device)
print('device_count: ', ngpus)

# velocities.shape
print('nchan: ', nchan)

cube_rs_all.shape

n_samples, n_channels = cube_rs_all.shape
print(f"Number of spectra: {n_samples}")
print(f"Number of channels: {n_channels}")

print(f"Training set: {n_samples} spectra with {n_channels} channels")
print(f"TB range: [{cube_rs_all.min():.2f}, {cube_rs_all.max():.2f}] K")
# print(f"True T_HI range: [{ts_cube_rs_all.min():.2f}, {ts_cube_rs_all.max():.2f}] K")
# print(f"True τ range: [{tau_cube_rs_all.min():.2f}, {tau_cube_rs_all.max():.2f}]")

n_train = 2094112
n_val = 528528
n_test = 20000

# Generate all possible indices
all_indices = np.arange(n_samples)

# Shuffle the indices
np.random.shuffle(all_indices)

# Split into two different sets of indices
train_indices = all_indices[:n_train]
val_indices = all_indices[n_train:(n_train + n_val)]
test_indices = all_indices[(n_train + n_val):(n_train + n_val + n_test)]


train_spectra = cube_rs_all[train_indices, :]
val_spectra = cube_rs_all[val_indices, :]
test_spectra = cube_rs_all[test_indices, :]
print(train_spectra.shape)
print(val_spectra.shape)
print(test_spectra.shape)

# train_tauspectra = tau_cube_rs_all[train_indices, :]
# val_tauspectra = tau_cube_rs_all[val_indices, :]
# test_tauspectra = tau_cube_rs_all[test_indices, :]
# print(train_tauspectra.shape)
# print(val_tauspectra.shape)
# print(test_tauspectra.shape)

# train_tempspectra = temp_log10_spectra[train_indices, :]
# val_tempspectra = temp_log10_spectra[val_indices, :]
# test_tempspectra = temp_log10_spectra[test_indices, :]
# print(train_tempspectra.shape)
# print(val_tempspectra.shape)
# print(test_tempspectra.shape)

# Hyperparameters
spectrum_dim = 256
latent_dim = 64  # 128 If reconstruction is still poor, reduce latent dimension further (try 16 or 8)
batch_size = 64

learning_rate = 1.e-4
num_epochs = 40
beta_max = 0.5 # 0.5  # Start with lower beta, Lower beta_max to prioritise reconstruction
beta_schedule = 'constant'  # Use beta annealing

# Create dataset and dataloader
dataset = HISpectrumDataset(train_spectra, normalize=False)
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

val_dataset = HISpectrumDataset(val_spectra, normalize=False)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

# Initialize model
# model = HI_VAE(spectrum_dim=spectrum_dim, hidden_dims=[512, 256, 128], latent_dim=latent_dim).to(device)
model = HI_VAE(spectrum_dim=spectrum_dim, latent_dim=latent_dim) #.to(device)

print(f"Model Architecture:")
print(model)
print(f"Total parameters: {sum(p.numel() for p in model.parameters()):,}")

# Train model
history = train_model(model, train_loader, val_loader, lr=learning_rate, device=device, num_epochs=num_epochs, beta_schedule=beta_schedule, beta_max=beta_max)

# Plot training history
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history['total_loss'], 'b-', lw=3, label='Train: total Loss')
plt.plot(history['recon_loss'], 'b--', lw=2, label='Train: reconstruction Loss')

plt.plot(history['val_total_loss'], 'r-', lw=3, label='Val: total Loss')
plt.plot(history['val_recon_loss'], 'r--', lw=2, label='Val: reconstruction Loss')
plt.yscale('log')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training/Validation Loss')
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.plot(history['kl_loss'], 'b-', lw=3, label='Train: KL divergence')
# plt.plot(history['sparse_loss'], label='Sparsity Loss')
plt.plot(history['ts_prior_loss'], 'b--', lw=2, label='Train: Ts prior loss')

plt.plot(history['val_kl_loss'], 'r-', lw=3,label='Val: KL divergence')
plt.plot(history['val_ts_prior_loss'], 'r--', lw=2, label='Val: Ts prior loss')

# plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('KL/Tspin Losses')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('best_vae_model_a00_smooth_mod11_mw_1100_1200.png', dpi=300, bbox_inches='tight')
plt.show()

"""# Predictions"""

# best_vae_model_a00_smooth_mod1
if False:
    saved_model_path = 'best_vae_model_a00_smooth_mod11_mw_1100_1200.pt'
    state_dict = torch.load(saved_model_path, map_location=torch.device(device))
    model.load_state_dict(state_dict)

    # model.eval()

    model.to(device)

    print("Model loaded successfully!")
"""# End"""